# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
    vmImage: 'Ubuntu-16.04'

trigger:
    - master

pr:
    - 'azure-pipelines'
    - 'azure-pipelines2'

steps:
    - task: DotNetCoreInstaller@0
    inputs:
        version:'2.2.1'
    - script:'dotnet restore ./DemoRepo/DemoRepo.sln'
    - script:'dotnet build ./DemoRepo/DemoRepo.sln'

#- task: ArchiveFiles@2
#  inputs:
#    rootFolderOrFile: '$(build.sourcesDirectory)'
#    includeRootFolder: false
#- task: PublishBuildArtifacts@1
